const keyTable = {
  "": { which: -1, key: "", caption: "", code: "none" },
  Backspace: { which: 8, key: "Backspace", caption: "⬅", code: "Backspace" },
  Tab: { which: 9, key: "Tab", caption: "⬅\u000A➡", code: "Tab" },
  Enter: { which: 13, key: "Enter", caption: "Enter", code: "Enter" },
  ShiftLeft: { which: 16, key: "Shift", caption: "⬆", code: "ShiftLeft", desc: "event.shiftKey is true" },
  ShiftRight: { which: 16, key: "Shift", caption: "⬆", code: "ShiftRight", desc: "event.shiftKey is true" },
  ControlLeft: { which: 17, key: "Control", caption: "Ctrl", code: "ControlLeft", desc: "event.ctrlKey is true" },
  ControlRight: { which: 17, key: "Control", caption: "Ctrl", code: "ControlRight", desc: "event.ctrlKey is true" },
  AltLeft: { which: 18, key: "Alt", caption: "Alt", code: "AltLeft", desc: "event.altKey is true" },
  AltRight: { which: 18, key: "Alt", caption: "Alt", code: "AltRight", desc: "event.altKey is true" },
  Pause: { which: 19, key: "Pause", caption: "Pause", code: "Pause" },
  CapsLock: { which: 20, key: "CapsLock", caption: "CapsLock", code: "CapsLock" },
  Escape: { which: 27, key: "Escape", caption: "Escape", code: "Escape" },
  Space: { which: 32, key: "", caption: "", code: "Space", desc: "The event.key value is a single space." },
  PageUp: { which: 33, key: "PageUp", caption: "PgUp", code: "PageUp" },
  PageDown: { which: 34, key: "PageDown", caption: "PgDn", code: "PageDown" },
  End: { which: 35, key: "End", caption: "End", code: "End" },
  Home: { which: 36, key: "Home", caption: "Home", code: "Home" },
  ArrowLeft: { which: 37, key: "ArrowLeft", caption: "⬅", code: "ArrowLeft" },
  ArrowUp: { which: 38, key: "ArrowUp", caption: "⬆", code: "ArrowUp" },
  ArrowRight: { which: 39, key: "ArrowRight", caption: "➡", code: "ArrowRight" },
  ArrowDown: { which: 40, key: "ArrowDown", caption: "⬇", code: "ArrowDown" },
  PrintScreen: { which: 44, key: "PrintScreen", caption: "PrtScr", code: "PrintScreen" },
  Insert: { which: 45, key: "Insert", caption: "Ins", code: "Insert" },
  Delete: { which: 46, key: "Delete", caption: "Del", code: "Delete" },
  Digit0: { which: 48, key: "0", caption: "0", code: "Digit0" },
  Digit1: { which: 49, key: "1", caption: "1", code: "Digit1" },
  Digit2: { which: 50, key: "2", caption: "2", code: "Digit2" },
  Digit3: { which: 51, key: "3", caption: "3", code: "Digit3" },
  Digit4: { which: 52, key: "4", caption: "4", code: "Digit4" },
  Digit5: { which: 53, key: "5", caption: "5", code: "Digit5" },
  Digit6: { which: 54, key: "6", caption: "6", code: "Digit6" },
  Digit7: { which: 55, key: "7", caption: "7", code: "Digit7" },
  Digit8: { which: 56, key: "8", caption: "8", code: "Digit8" },
  Digit9: { which: 57, key: "9", caption: "9", code: "Digit9" },
  KeyA: { which: 65, key: "a", caption: "A", code: "KeyA" },
  KeyB: { which: 66, key: "b", caption: "B", code: "KeyB" },
  KeyC: { which: 67, key: "c", caption: "C", code: "KeyC" },
  KeyD: { which: 68, key: "d", caption: "D", code: "KeyD" },
  KeyE: { which: 69, key: "e", caption: "E", code: "KeyE" },
  KeyF: { which: 70, key: "f", caption: "F", code: "KeyF" },
  KeyG: { which: 71, key: "g", caption: "G", code: "KeyG" },
  KeyH: { which: 72, key: "h", caption: "H", code: "KeyH" },
  KeyI: { which: 73, key: "i", caption: "I", code: "KeyI" },
  KeyJ: { which: 74, key: "j", caption: "J", code: "KeyJ" },
  KeyK: { which: 75, key: "k", caption: "K", code: "KeyK" },
  KeyL: { which: 76, key: "l", caption: "L", code: "KeyL" },
  KeyM: { which: 77, key: "m", caption: "M", code: "KeyM" },
  KeyN: { which: 78, key: "n", caption: "N", code: "KeyN" },
  KeyO: { which: 79, key: "o", caption: "O", code: "KeyO" },
  KeyP: { which: 80, key: "p", caption: "P", code: "KeyP" },
  KeyQ: { which: 81, key: "q", caption: "Q", code: "KeyQ" },
  KeyR: { which: 82, key: "r", caption: "R", code: "KeyR" },
  KeyS: { which: 83, key: "s", caption: "S", code: "KeyS" },
  KeyT: { which: 84, key: "t", caption: "T", code: "KeyT" },
  KeyU: { which: 85, key: "u", caption: "U", code: "KeyU" },
  KeyV: { which: 86, key: "v", caption: "V", code: "KeyV" },
  KeyW: { which: 87, key: "w", caption: "W", code: "KeyW" },
  KeyX: { which: 88, key: "x", caption: "X", code: "KeyX" },
  KeyY: { which: 89, key: "y", caption: "Y", code: "KeyY" },
  KeyZ: { which: 90, key: "z", caption: "Z", code: "KeyZ" },
  MetaLeft: { which: 91, key: "Meta", caption: "\u2756", code: "MetaLeft", desc: "event.metaKey is true" },
  MetaRight: { which: 92, key: "Meta", caption: "\u2756", code: "MetaRight", desc: "event.metaKey is true" },
  ContextMenu: { which: 93, key: "ContextMenu", caption: "ContextMenu", code: "ContextMenu" },
  Numpad0: { which: 96, key: "0", caption: "0", code: "Numpad0" },
  Numpad1: { which: 97, key: "1", caption: "1", code: "Numpad1" },
  Numpad2: { which: 98, key: "2", caption: "2", code: "Numpad2" },
  Numpad3: { which: 99, key: "3", caption: "3", code: "Numpad3" },
  Numpad4: { which: 100, key: "4", caption: "4", code: "Numpad4" },
  Numpad5: { which: 101, key: "5", caption: "5", code: "Numpad5" },
  Numpad6: { which: 102, key: "6", caption: "6", code: "Numpad6" },
  Numpad7: { which: 103, key: "7", caption: "7", code: "Numpad7" },
  Numpad8: { which: 104, key: "8", caption: "8", code: "Numpad8" },
  Numpad9: { which: 105, key: "9", caption: "9", code: "Numpad9" },
  NumpadMultiply: { which: 106, key: "*", caption: "*", code: "NumpadMultiply" },
  NumpadAdd: { which: 107, key: "+", caption: "+", code: "NumpadAdd" },
  NumpadSubtract: { which: 109, key: "-", caption: "-", code: "NumpadSubtract" },
  NumpadDecimal: { which: 110, key: ".", caption: ".", code: "NumpadDecimal" },
  NumpadDivide: { which: 111, key: "/", caption: "/", code: "NumpadDivide" },
  F1: { which: 112, key: "F1", caption: "F1", code: "F1" },
  F2: { which: 113, key: "F2", caption: "F2", code: "F2" },
  F3: { which: 114, key: "F3", caption: "F3", code: "F3" },
  F4: { which: 115, key: "F4", caption: "F4", code: "F4" },
  F5: { which: 116, key: "F5", caption: "F5", code: "F5" },
  F6: { which: 117, key: "F6", caption: "F6", code: "F6" },
  F7: { which: 118, key: "F7", caption: "F7", code: "F7" },
  F8: { which: 119, key: "F8", caption: "F8", code: "F8" },
  F9: { which: 120, key: "F9", caption: "F9", code: "F9" },
  F10: { which: 121, key: "F10", caption: "F10", code: "F10" },
  F11: { which: 122, key: "F11", caption: "F11", code: "F11" },
  F12: { which: 123, key: "F12", caption: "F12", code: "F12" },
  NumLock: { which: 144, key: "NumLock", caption: "NumLock", code: "NumLock" },
  ScrollLock: { which: 145, key: "ScrollLock", caption: "ScrollLock", code: "ScrollLock" },
  Semicolon: {
    which: 186,
    key: ";",
    caption: ";",
    code: "Semicolon",
    desc: "⚠️ The event.which value is 59 in Firefox",
  },
  Equal: { which: 187, key: "=", caption: "=", code: "Equal", desc: "⚠️ The event.which value is 61 in Firefox" },
  Comma: { which: 188, key: ",", caption: ",", code: "Comma" },
  Minus: { which: 189, key: "-", caption: "-", code: "Minus", desc: "⚠️ The event.which value is 173 in Firefox" },
  Period: { which: 190, key: ".", caption: ".", code: "Period" },
  Slash: { which: 191, key: "/", caption: "/", code: "Slash" },
  Backquote: { which: 192, key: "`", caption: "`", code: "Backquote" },
  BracketLeft: { which: 219, key: "[", caption: "[", code: "BracketLeft" },
  Backslash: { which: 220, key: "\\", caption: "\\", code: "Backslash" },
  IntlBackslash: { which: 220, key: "\\", caption: "\\", code: "Backslash" },
  BracketRight: { which: 221, key: "]", caption: "]", code: "BracketRight" },
  Quote: { which: 222, key: "'", caption: "'", code: "Quote" },

  // non-standard keys
  NumpadEnter: { which: 13, key: "Enter", caption: "Enter", code: "NumpadEnter" },
};

export const keyOrder: Array<keyof typeof keyTable> = [
  "Escape",
  "",

  "F1",
  "F2",
  "F3",
  "F4",
  "",
  "F5",
  "F6",
  "F7",
  "F8",
  "",
  "F9",
  "F10",
  "F11",
  "F12",
  "",
  "PrintScreen",
  "ScrollLock",
  "Pause",
  "",
  "",
  "",
  "",
  "",
  "",

  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",

  "Backquote",
  "Digit1",
  "Digit2",
  "Digit3",
  "Digit4",
  "Digit5",
  "Digit6",
  "Digit7",
  "Digit8",
  "Digit9",
  "Digit0",
  "Minus",
  "Equal",
  "Backspace",
  "",
  "Insert",
  "Home",
  "PageUp",
  "",
  "NumLock",
  "NumpadDivide",
  "NumpadMultiply",
  "NumpadSubtract",

  "Tab",
  "KeyQ",
  "KeyW",
  "KeyE",
  "KeyR",
  "KeyT",
  "KeyY",
  "KeyU",
  "KeyI",
  "KeyO",
  "KeyP",
  "BracketLeft",
  "BracketRight",
  "Enter",
  "",
  "Delete",
  "End",
  "PageDown",
  "",
  "Numpad7",
  "Numpad8",
  "Numpad9",
  "NumpadAdd",

  "CapsLock",
  "KeyA",
  "KeyS",
  "KeyD",
  "KeyF",
  "KeyG",
  "KeyH",
  "KeyJ",
  "KeyK",
  "KeyL",
  "Semicolon",
  "Quote",
  "Backslash",

  "",
  "",
  "",
  "",
  "",
  "",

  "Numpad4",
  "Numpad5",
  "Numpad6",

  "ShiftLeft",
  "Backslash",
  "KeyZ",
  "KeyX",
  "KeyC",
  "KeyV",
  "KeyB",
  "KeyN",
  "KeyM",
  "Comma",
  "Period",
  "Slash",
  "ShiftRight",
  "",
  "",
  "ArrowUp",
  "",
  "",
  "Numpad1",
  "Numpad2",
  "Numpad3",
  "NumpadEnter",

  "ControlLeft",
  "MetaLeft",
  "AltLeft",
  "Space",
  "AltRight",
  "MetaRight",
  "ContextMenu",
  "ControlRight",

  "",
  "ArrowLeft",
  "ArrowDown",
  "ArrowRight",
  "",

  "Numpad0",
  "NumpadDecimal",
];

export type KeyIndex = keyof typeof keyTable;

export type ModKey =
  | "AltLeft"
  | "AltRight"
  | "ControlLeft"
  | "ControlRight"
  | "ShiftLeft"
  | "ShiftRight"
  | "MetaLeft"
  | "MetaRight";

export default keyTable;
