export const keyTable = [
  { name: "backspace",                 which: 8,   key: "Backspace",   code: "Backspace" },
  { name: "tab",                       which: 9,   key: "Tab",         code: "Tab" },
  { name: "enter",                     which: 13,  key: "Enter",       code: "Enter" },
  { name: "shift_left",                which: 16,  key: "Shift",       code: "ShiftLeft" },
  { name: "shift_right",               which: 16,  key: "Shift",       code: "ShiftRight" },
  { name: "ctrl_left",                 which: 17,  key: "Control",     code: "ControlLeft" },
  { name: "ctrl_right",                which: 17,  key: "Control",     code: "ControlRight" },
  { name: "alt_left",                  which: 18,  key: "Alt",         code: "AltLeft" },
  { name: "alt_right",                 which: 18,  key: "Alt",         code: "AltRight" },
  { name: "pause",                     which: 19,  key: "Pause",       code: "Pause" },
  { name: "caps lock",                 which: 20,  key: "CapsLock",    code: "CapsLock" },
  { name: "escape",                    which: 27,  key: "Escape",      code: "Escape" },
  { name: "space",                     which: 32,  key: " ",           code: "Space" },
  { name: "page up",                   which: 33,  key: "PageUp",      code: "PageUp" },
  { name: "page down",                 which: 34,  key: "PageDown",    code: "PageDown" },
  { name: "end",                       which: 35,  key: "End",         code: "End" },
  { name: "home",                      which: 36,  key: "Home",        code: "Home" },
  { name: "left arrow",                which: 37,  key: "ArrowLeft",   code: "ArrowLeft" },
  { name: "up arrow",                  which: 38,  key: "ArrowUp",     code: "ArrowUp" },
  { name: "right arrow",               which: 39,  key: "ArrowRight",  code: "ArrowRight" },
  { name: "down arrow",                which: 40,  key: "ArrowDown",   code: "ArrowDown" },
  { name: "print screen",              which: 44,  key: "PrintScreen", code: "PrintScreen" },
  { name: "insert",                    which: 45,  key: "Insert",      code: "Insert" },
  { name: "delete",                    which: 46,  key: "Delete",      code: "Delete" },
  { name: "0",                         which: 48,  key: "0",           code: "Digit0" },
  { name: "1",                         which: 49,  key: "1",           code: "Digit1" },
  { name: "2",                         which: 50,  key: "2",           code: "Digit2" },
  { name: "3",                         which: 51,  key: "3",           code: "Digit3" },
  { name: "4",                         which: 52,  key: "4",           code: "Digit4" },
  { name: "5",                         which: 53,  key: "5",           code: "Digit5" },
  { name: "6",                         which: 54,  key: "6",           code: "Digit6" },
  { name: "7",                         which: 55,  key: "7",           code: "Digit7" },
  { name: "8",                         which: 56,  key: "8",           code: "Digit8" },
  { name: "9",                         which: 57,  key: "9",           code: "Digit9" },
  { name: "a",                         which: 65,  key: "a",           code: "KeyA" },
  { name: "b",                         which: 66,  key: "b",           code: "KeyB" },
  { name: "c",                         which: 67,  key: "c",           code: "KeyC" },
  { name: "d",                         which: 68,  key: "d",           code: "KeyD" },
  { name: "e",                         which: 69,  key: "e",           code: "KeyE" },
  { name: "f",                         which: 70,  key: "f",           code: "KeyF" },
  { name: "g",                         which: 71,  key: "g",           code: "KeyG" },
  { name: "h",                         which: 72,  key: "h",           code: "KeyH" },
  { name: "i",                         which: 73,  key: "i",           code: "KeyI" },
  { name: "j",                         which: 74,  key: "j",           code: "KeyJ" },
  { name: "k",                         which: 75,  key: "k",           code: "KeyK" },
  { name: "l",                         which: 76,  key: "l",           code: "KeyL" },
  { name: "m",                         which: 77,  key: "m",           code: "KeyM" },
  { name: "n",                         which: 78,  key: "n",           code: "KeyN" },
  { name: "o",                         which: 79,  key: "o",           code: "KeyO" },
  { name: "p",                         which: 80,  key: "p",           code: "KeyP" },
  { name: "q",                         which: 81,  key: "q",           code: "KeyQ" },
  { name: "r",                         which: 82,  key: "r",           code: "KeyR" },
  { name: "s",                         which: 83,  key: "s",           code: "KeyS" },
  { name: "t",                         which: 84,  key: "t",           code: "KeyT" },
  { name: "u",                         which: 85,  key: "u",           code: "KeyU" },
  { name: "v",                         which: 86,  key: "v",           code: "KeyV" },
  { name: "w",                         which: 87,  key: "w",           code: "KeyW" },
  { name: "x",                         which: 88,  key: "x",           code: "KeyX" },
  { name: "y",                         which: 89,  key: "y",           code: "KeyY" },
  { name: "z",                         which: 90,  key: "z",           code: "KeyZ" },
  { name: "left window key",           which: 91,  key: "Meta",        code: "MetaLeft" },
  { name: "right window key",          which: 92,  key: "Meta",        code: "MetaRight" },
  { name: "select key _ContextMenu)", which: 93,  key: "ContextMenu", code: "ContextMenu" },
  { name: "numpad 0",                  which: 96,  key: "0",           code: "Numpad0" },
  { name: "numpad 1",                  which: 97,  key: "1",           code: "Numpad1" },
  { name: "numpad 2",                  which: 98,  key: "2",           code: "Numpad2" },
  { name: "numpad 3",                  which: 99,  key: "3",           code: "Numpad3" },
  { name: "numpad 4",                  which: 100, key: "4",           code: "Numpad4" },
  { name: "numpad 5",                  which: 101, key: "5",           code: "Numpad5" },
  { name: "numpad 6",                  which: 102, key: "6",           code: "Numpad6" },
  { name: "numpad 7",                  which: 103, key: "7",           code: "Numpad7" },
  { name: "numpad 8",                  which: 104, key: "8",           code: "Numpad8" },
  { name: "numpad 9",                  which: 105, key: "9",           code: "Numpad9" },
  { name: "multiply",                  which: 106, key: "*",           code: "NumpadMultiply" },
  { name: "add",                       which: 107, key: "+",           code: "NumpadAdd" },
  { name: "subtract",                  which: 109, key: "-",           code: "NumpadSubtract" },
  { name: "decimal point",             which: 110, key: ".",           code: "NumpadDecimal" },
  { name: "divide",                    which: 111, key: "/",           code: "NumpadDivide" },
  { name: "f1",                        which: 112, key: "F1",          code: "F1" },
  { name: "f2",                        which: 113, key: "F2",          code: "F2" },
  { name: "f3",                        which: 114, key: "F3",          code: "F3" },
  { name: "f4",                        which: 115, key: "F4",          code: "F4" },
  { name: "f5",                        which: 116, key: "F5",          code: "F5" },
  { name: "f6",                        which: 117, key: "F6",          code: "F6" },
  { name: "f7",                        which: 118, key: "F7",          code: "F7" },
  { name: "f8",                        which: 119, key: "F8",          code: "F8" },
  { name: "f9",                        which: 120, key: "F9",          code: "F9" },
  { name: "f10",                       which: 121, key: "F10",         code: "F10" },
  { name: "f11",                       which: 122, key: "F11",         code: "F11" },
  { name: "f12",                       which: 123, key: "F12",         code: "F12" },
  { name: "num lock",                  which: 144, key: "NumLock",     code: "NumLock" },
  { name: "scroll lock",               which: 145, key: "ScrollLock",  code: "ScrollLock" },
  { name: "semi-colon",                which: 186, key: ";",           code: "Semicolon" },
  { name: "equal sign",                which: 187, key: "=",           code: "Equal" },
  { name: "comma",                     which: 188, key: ",",           code: "Comma" },
  { name: "dash",                      which: 189, key: "-",           code: "Minus" },
  { name: "period",                    which: 190, key: ".",           code: "Period" },
  { name: "forward slash",             which: 191, key: "/",           code: "Slash" },
  { name: "Backquote/Grave accent",    which: 192, key: "`",           code: "Backquote" },
  { name: "open bracket",              which: 219, key: "[",           code: "BracketLeft" },
  { name: "back slash",                which: 220, key: "\\",          code: "Backslash" },
  { name: "close bracket",             which: 221, key: "]",           code: "BracketRight" },
  { name: "single quote",              which: 222, key: "'",           code: "Quote" },
];

const keys = {
  "": { caption: "", keycode: 0 },
  "{half}": { caption: "", keycode: 0 },
  backquote: { caption: "`", keycode: 192 },
  minus: { caption: "-", keycode: 189 },
  equal: { caption: "=", keycode: 188 },
  "0": { caption: "0", keycode: 48 },
  "1": { caption: "1", keycode: 49 },
  "2": { caption: "2", keycode: 50 },
  "3": { caption: "3", keycode: 51 },
  "4": { caption: "4", keycode: 52 },
  "5": { caption: "5", keycode: 53 },
  "6": { caption: "6", keycode: 54 },
  "7": { caption: "7", keycode: 55 },
  "8": { caption: "8", keycode: 56 },
  "9": { caption: "9", keycode: 57 },
  backspace: { caption: "⬅", keycode: 8 },
  tab: { caption: "⬅\u000A➡", keycode: 9 },
  enter: { caption: "↩", keycode: 13 },
  shift: { caption: "⬆", keycode: 16 },
  shift_right: { caption: "⬆", keycode: 16 },
  ctrl: { caption: "Ctrl", keycode: 17 },
  alt: { caption: "Alt", keycode: 18 },
  alt_right: { caption: "Alt", keycode: 18 },
  pause_break: { caption: "pause_break", keycode: 19 },
  caps_lock: { caption: "CAPS", keycode: 20 },
  escape: { caption: "Esc", keycode: 27 },
  page_up: { caption: "PgUp", keycode: 33 },
  page_down: { caption: "PgDn", keycode: 34 },
  end: { caption: "End", keycode: 35 },
  home: { caption: "Home", keycode: 36 },
  left_arrow: { caption: "⬅", keycode: 37 },
  up_arrow: { caption: "⬆", keycode: 38 },
  right_arrow: { caption: "➡", keycode: 39 },
  down_arrow: { caption: "⬇", keycode: 40 },
  insert: { caption: "Ins", keycode: 45 },
  delete: { caption: "Del", keycode: 46 },
  a: { caption: "A", keycode: 65 },
  b: { caption: "B", keycode: 66 },
  c: { caption: "C", keycode: 67 },
  d: { caption: "D", keycode: 68 },
  e: { caption: "E", keycode: 69 },
  f: { caption: "F", keycode: 70 },
  g: { caption: "G", keycode: 71 },
  h: { caption: "H", keycode: 72 },
  i: { caption: "I", keycode: 73 },
  j: { caption: "J", keycode: 74 },
  k: { caption: "K", keycode: 75 },
  l: { caption: "L", keycode: 76 },
  m: { caption: "M", keycode: 77 },
  n: { caption: "N", keycode: 78 },
  o: { caption: "O", keycode: 79 },
  p: { caption: "P", keycode: 80 },
  q: { caption: "Q", keycode: 81 },
  r: { caption: "R", keycode: 82 },
  s: { caption: "S", keycode: 83 },
  t: { caption: "T", keycode: 84 },
  u: { caption: "U", keycode: 85 },
  v: { caption: "V", keycode: 86 },
  w: { caption: "W", keycode: 87 },
  x: { caption: "X", keycode: 88 },
  y: { caption: "Y", keycode: 89 },
  z: { caption: "Z", keycode: 90 },
  left_window_key: { caption: "\u2756", keycode: 91 },
  right_window_key: { caption: "\u2756", keycode: 92 },
  select_key: { caption: "select_key", keycode: 93 },
  numpad_0: { caption: "0", keycode: 96 },
  numpad_1: { caption: "1", keycode: 97 },
  numpad_2: { caption: "2", keycode: 98 },
  numpad_3: { caption: "3", keycode: 99 },
  numpad_4: { caption: "4", keycode: 100 },
  numpad_5: { caption: "5", keycode: 101 },
  numpad_6: { caption: "6", keycode: 102 },
  numpad_7: { caption: "7", keycode: 103 },
  numpad_8: { caption: "8", keycode: 104 },
  numpad_9: { caption: "9", keycode: 105 },
  multiply: { caption: "*", keycode: 106 },
  add: { caption: "+", keycode: 107 },
  subtract: { caption: "-", keycode: 109 },
  decimal_point: { caption: ".", keycode: 110 },
  divide: { caption: "/", keycode: 111 },
  f1: { caption: "f1", keycode: 112 },
  f2: { caption: "f2", keycode: 113 },
  f3: { caption: "f3", keycode: 114 },
  f4: { caption: "f4", keycode: 115 },
  f5: { caption: "f5", keycode: 116 },
  f6: { caption: "f6", keycode: 117 },
  f7: { caption: "f7", keycode: 118 },
  f8: { caption: "f8", keycode: 119 },
  f9: { caption: "f9", keycode: 120 },
  f10: { caption: "f10", keycode: 121 },
  f11: { caption: "f11", keycode: 122 },
  f12: { caption: "f12", keycode: 123 },
  num_lock: { caption: "Num", keycode: 144 },
  scroll_lock: { caption: "Scroll", keycode: 145 },
  semi_colon: { caption: ";", keycode: 186 },
  equal_sign: { caption: "=", keycode: 187 },
  comma: { caption: ",", keycode: 188 },
  dash: { caption: "-", keycode: 189 },
  period: { caption: ".", keycode: 190 },
  forward_slash: { caption: "/", keycode: 191 },
  grave_accent: { caption: "`", keycode: 192 },
  open_bracket: { caption: "[", keycode: 219 },
  back_slash: { caption: "\\", keycode: 220 },
  close_bracket: { caption: "]", keycode: 221 },
  single_quote: { caption: "'", keycode: 222 },
  numpad_enter: { caption: "Enter", keycode: 176 },
  numpad_subtract: { caption: "-", keycode: 109 },
  space: { caption: "Space", keycode: 32 },
  context_menu: { caption: "☰", keycode: 93 },
  control_right: { caption: "Ctrl", keycode: 17 },
  numpad_period: { caption: ".", keycode: 190 },
  print_screen: { caption: "PrtSc", keycode: 44 },
  pause: { caption: "Pause", keycode: 19 },
};

export const keyOrder: Array<keyof typeof keys> = [
  "escape",
  "",

  "f1",
  "f2",
  "f3",
  "f4",
  "",
  "f5",
  "f6",
  "f7",
  "f8",
  "",
  "f9",
  "f10",
  "f11",
  "f12",
  "",
  "print_screen",
  "scroll_lock",
  "pause",
  "",
  "",
  "",
  "",
  "",
  "",

  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",

  "backquote",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "minus",
  "equal",
  "backspace",
  "",
  "insert",
  "home",
  "page_up",
  "",
  "num_lock",
  "divide",
  "multiply",
  "numpad_subtract",

  "tab",
  "q",
  "w",
  "e",
  "r",
  "t",
  "y",
  "u",
  "i",
  "o",
  "p",
  "open_bracket",
  "close_bracket",
  "enter",
  "",
  "delete",
  "end",
  "page_down",
  "",
  "numpad_7",
  "numpad_8",
  "numpad_9",
  "add",

  "caps_lock",
  "a",
  "s",
  "d",
  "f",
  "g",
  "h",
  "j",
  "k",
  "l",
  "semi_colon",
  "single_quote",
  "back_slash",

  "",
  "",
  "",
  "",
  "",
  "",

  "numpad_4",
  "numpad_5",
  "numpad_6",

  "shift",
  "back_slash",
  "z",
  "x",
  "c",
  "v",
  "b",
  "n",
  "m",
  "comma",
  "period",
  "forward_slash",
  "shift_right",
  "",
  "",
  "up_arrow",
  "",
  "",
  "numpad_1",
  "numpad_2",
  "numpad_3",
  "numpad_enter",

  "ctrl",
  "left_window_key",
  "alt",
  "space",
  "alt_right",
  "right_window_key",
  "context_menu",
  "control_right",

  "",
  "left_arrow",
  "down_arrow",
  "right_arrow",
  "",

  "numpad_0",
  "numpad_period",
];

export type KeyIndex = keyof typeof keys;

export default keys;
